#!/usr/bin/env python3
"""Report screen-space SVG point residuals against a Graphviz oracle.

The script compares ordered ``polygon``, ``polyline``, and ``path`` point
streams after accumulating each SVG's graph ``translate(...)`` transform.
Optionally, it also compares ``text`` anchor positions. It is intended for
Graphviz parity work on fixtures such as assets/test000.svg.
"""

from __future__ import annotations

import argparse
import math
import re
from pathlib import Path


TAG_RE = re.compile(r"<(polygon|polyline|path)\b[^>]*>")
TEXT_RE = re.compile(r"<text\b([^>]*)>(.*?)</text>")
NUM_RE = re.compile(r"-?\d+(?:\.\d+)?")
TRANSLATE_RE = re.compile(r"translate\(([^)]*)\)")


def graph_translate(svg: str) -> tuple[float, float]:
    x = 0.0
    y = 0.0
    for match in TRANSLATE_RE.finditer(svg):
        values = re.split(r"[ ,]+", match.group(1).strip())
        if len(values) >= 2:
            x += float(values[0])
            y += float(values[1])
    return x, y


def numbers_in_attr(tag: str, attr: str) -> list[float]:
    match = re.search(rf'\s{attr}="([^"]*)"', tag)
    if not match:
        return []
    return [float(value) for value in NUM_RE.findall(match.group(1))]


def drawable_points(svg: str) -> list[tuple[str, list[tuple[float, float]], str]]:
    tx, ty = graph_translate(svg)
    result: list[tuple[str, list[tuple[float, float]], str]] = []
    for match in TAG_RE.finditer(svg):
        tag_name = match.group(1)
        tag_text = match.group(0)
        attr = "d" if tag_name == "path" else "points"
        nums = numbers_in_attr(tag_text, attr)
        if len(nums) < 2 or len(nums) % 2 != 0:
            continue
        points = [(nums[i] + tx, nums[i + 1] + ty) for i in range(0, len(nums), 2)]
        result.append((tag_name, points, tag_text))
    return result


def text_points(svg: str) -> list[tuple[str, list[tuple[float, float]], str]]:
    tx, ty = graph_translate(svg)
    result: list[tuple[str, list[tuple[float, float]], str]] = []
    for match in TEXT_RE.finditer(svg):
        attrs = match.group(1)
        text = re.sub(r"<[^>]+>", "", match.group(2))
        x_match = re.search(r'\sx="([^"]*)"', attrs)
        y_match = re.search(r'\sy="([^"]*)"', attrs)
        if not x_match or not y_match:
            continue
        point = (float(x_match.group(1)) + tx, float(y_match.group(1)) + ty)
        result.append((f"text:{text}", [point], match.group(0)))
    return result


def one_decimal_lower_bound(point: tuple[float, float]) -> float:
    x, y = point
    best = math.inf
    for xi in range(math.floor(x * 10) - 2, math.ceil(x * 10) + 3):
        for yi in range(math.floor(y * 10) - 2, math.ceil(y * 10) + 3):
            best = min(best, math.hypot(xi / 10 - x, yi / 10 - y))
    return best


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("svg", type=Path, help="SVG generated by Vex")
    parser.add_argument("oracle", type=Path, help="Graphviz oracle SVG")
    parser.add_argument("--top", type=int, default=20, help="number of largest residuals to print")
    parser.add_argument("--include-text", action="store_true", help="also compare text anchor positions")
    parser.add_argument(
        "--max-residual",
        type=float,
        default=None,
        help="exit with status 1 if the maximum residual exceeds this value",
    )
    parser.add_argument(
        "--show-lower-bound",
        action="store_true",
        help="show the best possible residual on a one-decimal coordinate grid",
    )
    parser.add_argument(
        "--skip-background",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="skip the root background polygon; Vex and Graphviz use opposite coordinate directions there",
    )
    args = parser.parse_args()

    svg = args.svg.read_text()
    oracle = args.oracle.read_text()
    drawables = drawable_points(svg)
    oracle_drawables = drawable_points(oracle)
    if args.skip_background:
        drawables = drawables[1:]
        oracle_drawables = oracle_drawables[1:]
    if args.include_text:
        drawables.extend(text_points(svg))
        oracle_drawables.extend(text_points(oracle))

    if len(drawables) != len(oracle_drawables):
        raise SystemExit(f"drawable count mismatch: {len(drawables)} != {len(oracle_drawables)}")

    rows: list[tuple[float, int, str, int, tuple[float, float], tuple[float, float], str]] = []
    for drawable_index, ((tag, points, tag_text), (oracle_tag, oracle_points, _)) in enumerate(
        zip(drawables, oracle_drawables),
        start=1 if args.skip_background else 0,
    ):
        if tag != oracle_tag:
            raise SystemExit(f"tag mismatch at drawable {drawable_index}: {tag} != {oracle_tag}")
        if len(points) != len(oracle_points):
            raise SystemExit(
                f"point count mismatch at drawable {drawable_index} ({tag}): "
                f"{len(points)} != {len(oracle_points)}"
            )
        for point_index, (point, oracle_point) in enumerate(zip(points, oracle_points)):
            residual = math.hypot(point[0] - oracle_point[0], point[1] - oracle_point[1])
            rows.append((residual, drawable_index, tag, point_index, point, oracle_point, tag_text))

    rows.sort(reverse=True, key=lambda row: row[0])
    max_residual = rows[0][0] if rows else 0.0
    print(f"max_residual={max_residual:.4f} drawable_count={len(drawables)} point_count={len(rows)}")
    for residual, drawable_index, tag, point_index, point, oracle_point, tag_text in rows[: args.top]:
        dx = point[0] - oracle_point[0]
        dy = point[1] - oracle_point[1]
        lower_bound = one_decimal_lower_bound(oracle_point) if args.show_lower_bound else None
        lower_bound_text = (
            f" lower_bound={lower_bound:.4f} gap={residual - lower_bound:.4f}"
            if lower_bound is not None
            else ""
        )
        print(
            f"{residual:.4f} drawable={drawable_index} tag={tag} point={point_index} "
            f"delta=({dx:.4f},{dy:.4f}) point=({point[0]:.4f},{point[1]:.4f}) "
            f"oracle=({oracle_point[0]:.4f},{oracle_point[1]:.4f}){lower_bound_text}"
        )
        print(f"  {tag_text[:120]}")
    if args.max_residual is not None and max_residual > args.max_residual:
        raise SystemExit(
            f"max residual {max_residual:.4f} exceeds limit {args.max_residual:.4f}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
