//! Deterministic text metrics used by the native layout engine.
//!
//! Vex does not consult host font discovery while laying out a graph. Tables in
//! this module are therefore deliberately embedded and tied to a documented
//! reference face rather than making runtime output depend on Fontconfig.

const std = @import("std");

const SymbolMetric = struct {
    codepoint: u21,
    /// Advance at 14pt in quarter-point units.
    quarter_points: u8,
};

/// Returns the maximum line advance for Graphviz's PostScript `Symbol` face.
///
/// The table below was generated from the Pango logical advances of
/// StandardSymbolsPS.otf, Graphviz's metric-compatible Symbol resolution on
/// Linux, at its 96dpi text-layout resolution. Pango hint metrics quantize
/// those 14pt advances to quarter points. Graphviz 2.42 then rounded each
/// complete line up with `(int)(advance + 1)` before shape fitting; Vex follows
/// that contract while remaining independent of the host's installed fonts.
pub fn symbolLabelWidth(text: []const u8, font_size: f64) ?f64 {
    if (!std.unicode.utf8ValidateSlice(text)) return null;

    var line_width: f64 = 0;
    var max_width: f64 = 0;
    var iterator = std.unicode.Utf8View.initUnchecked(text).iterator();
    while (iterator.nextCodepoint()) |codepoint| {
        if (isLineBreak(codepoint)) {
            max_width = @max(max_width, line_width);
            line_width = 0;
            continue;
        }
        if (codepoint == '\t') {
            line_width += @as(f64, symbolAdvanceQuarterPoints(' ') orelse return null) * 4.0;
        } else {
            line_width += @as(f64, symbolAdvanceQuarterPoints(codepoint) orelse return null);
        }
    }
    const pango_width = @max(max_width, line_width) * 0.25 * font_size / 14.0;
    return @floor(pango_width + 1.0);
}

fn isLineBreak(codepoint: u21) bool {
    // Vex lowers Graphviz \l and \r to these private control bytes.
    return codepoint == '\n' or codepoint == 0x1e or codepoint == 0x1f;
}

fn symbolAdvanceQuarterPoints(codepoint: u21) ?u8 {
    var low: usize = 0;
    var high: usize = symbol_metrics.len;
    while (low < high) {
        const mid = low + (high - low) / 2;
        const metric = symbol_metrics[mid];
        if (codepoint < metric.codepoint) {
            high = mid;
        } else if (codepoint > metric.codepoint) {
            low = mid + 1;
        } else {
            return metric.quarter_points;
        }
    }
    return null;
}

// Generated from StandardSymbolsPS.otf Pango logical advances at 14pt/96dpi.
// Entries cover printable ASCII plus every codepoint reachable through the
// HTML 4 entity set accepted by the DOT parser.
const symbol_metrics = [_]SymbolMetric{
    .{ .codepoint = 0x20, .quarter_points = 15 },
    .{ .codepoint = 0x21, .quarter_points = 18 },
    .{ .codepoint = 0x22, .quarter_points = 39 },
    .{ .codepoint = 0x23, .quarter_points = 27 },
    .{ .codepoint = 0x24, .quarter_points = 30 },
    .{ .codepoint = 0x25, .quarter_points = 48 },
    .{ .codepoint = 0x26, .quarter_points = 45 },
    .{ .codepoint = 0x27, .quarter_points = 24 },
    .{ .codepoint = 0x28, .quarter_points = 18 },
    .{ .codepoint = 0x29, .quarter_points = 18 },
    .{ .codepoint = 0x2A, .quarter_points = 27 },
    .{ .codepoint = 0x2B, .quarter_points = 30 },
    .{ .codepoint = 0x2C, .quarter_points = 15 },
    .{ .codepoint = 0x2D, .quarter_points = 30 },
    .{ .codepoint = 0x2E, .quarter_points = 15 },
    .{ .codepoint = 0x2F, .quarter_points = 15 },
    .{ .codepoint = 0x30, .quarter_points = 27 },
    .{ .codepoint = 0x31, .quarter_points = 27 },
    .{ .codepoint = 0x32, .quarter_points = 27 },
    .{ .codepoint = 0x33, .quarter_points = 27 },
    .{ .codepoint = 0x34, .quarter_points = 27 },
    .{ .codepoint = 0x35, .quarter_points = 27 },
    .{ .codepoint = 0x36, .quarter_points = 27 },
    .{ .codepoint = 0x37, .quarter_points = 27 },
    .{ .codepoint = 0x38, .quarter_points = 27 },
    .{ .codepoint = 0x39, .quarter_points = 27 },
    .{ .codepoint = 0x3A, .quarter_points = 15 },
    .{ .codepoint = 0x3B, .quarter_points = 15 },
    .{ .codepoint = 0x3C, .quarter_points = 30 },
    .{ .codepoint = 0x3D, .quarter_points = 30 },
    .{ .codepoint = 0x3E, .quarter_points = 30 },
    .{ .codepoint = 0x3F, .quarter_points = 24 },
    .{ .codepoint = 0x40, .quarter_points = 30 },
    .{ .codepoint = 0x41, .quarter_points = 39 },
    .{ .codepoint = 0x42, .quarter_points = 36 },
    .{ .codepoint = 0x43, .quarter_points = 39 },
    .{ .codepoint = 0x44, .quarter_points = 33 },
    .{ .codepoint = 0x45, .quarter_points = 33 },
    .{ .codepoint = 0x46, .quarter_points = 42 },
    .{ .codepoint = 0x47, .quarter_points = 33 },
    .{ .codepoint = 0x48, .quarter_points = 39 },
    .{ .codepoint = 0x49, .quarter_points = 18 },
    .{ .codepoint = 0x4A, .quarter_points = 36 },
    .{ .codepoint = 0x4B, .quarter_points = 39 },
    .{ .codepoint = 0x4C, .quarter_points = 39 },
    .{ .codepoint = 0x4D, .quarter_points = 51 },
    .{ .codepoint = 0x4E, .quarter_points = 39 },
    .{ .codepoint = 0x4F, .quarter_points = 39 },
    .{ .codepoint = 0x50, .quarter_points = 42 },
    .{ .codepoint = 0x51, .quarter_points = 42 },
    .{ .codepoint = 0x52, .quarter_points = 30 },
    .{ .codepoint = 0x53, .quarter_points = 33 },
    .{ .codepoint = 0x54, .quarter_points = 33 },
    .{ .codepoint = 0x55, .quarter_points = 39 },
    .{ .codepoint = 0x56, .quarter_points = 24 },
    .{ .codepoint = 0x57, .quarter_points = 42 },
    .{ .codepoint = 0x58, .quarter_points = 36 },
    .{ .codepoint = 0x59, .quarter_points = 45 },
    .{ .codepoint = 0x5A, .quarter_points = 33 },
    .{ .codepoint = 0x5B, .quarter_points = 18 },
    .{ .codepoint = 0x5C, .quarter_points = 48 },
    .{ .codepoint = 0x5D, .quarter_points = 18 },
    .{ .codepoint = 0x5E, .quarter_points = 36 },
    .{ .codepoint = 0x5F, .quarter_points = 27 },
    .{ .codepoint = 0x60, .quarter_points = 27 },
    .{ .codepoint = 0x61, .quarter_points = 36 },
    .{ .codepoint = 0x62, .quarter_points = 30 },
    .{ .codepoint = 0x63, .quarter_points = 30 },
    .{ .codepoint = 0x64, .quarter_points = 27 },
    .{ .codepoint = 0x65, .quarter_points = 24 },
    .{ .codepoint = 0x66, .quarter_points = 30 },
    .{ .codepoint = 0x67, .quarter_points = 24 },
    .{ .codepoint = 0x68, .quarter_points = 33 },
    .{ .codepoint = 0x69, .quarter_points = 18 },
    .{ .codepoint = 0x6A, .quarter_points = 33 },
    .{ .codepoint = 0x6B, .quarter_points = 30 },
    .{ .codepoint = 0x6C, .quarter_points = 30 },
    .{ .codepoint = 0x6D, .quarter_points = 33 },
    .{ .codepoint = 0x6E, .quarter_points = 30 },
    .{ .codepoint = 0x6F, .quarter_points = 30 },
    .{ .codepoint = 0x70, .quarter_points = 30 },
    .{ .codepoint = 0x71, .quarter_points = 30 },
    .{ .codepoint = 0x72, .quarter_points = 30 },
    .{ .codepoint = 0x73, .quarter_points = 33 },
    .{ .codepoint = 0x74, .quarter_points = 24 },
    .{ .codepoint = 0x75, .quarter_points = 33 },
    .{ .codepoint = 0x76, .quarter_points = 39 },
    .{ .codepoint = 0x77, .quarter_points = 39 },
    .{ .codepoint = 0x78, .quarter_points = 27 },
    .{ .codepoint = 0x79, .quarter_points = 39 },
    .{ .codepoint = 0x7A, .quarter_points = 27 },
    .{ .codepoint = 0x7B, .quarter_points = 27 },
    .{ .codepoint = 0x7C, .quarter_points = 12 },
    .{ .codepoint = 0x7D, .quarter_points = 27 },
    .{ .codepoint = 0x7E, .quarter_points = 30 },
    .{ .codepoint = 0xA0, .quarter_points = 42 },
    .{ .codepoint = 0xA1, .quarter_points = 36 },
    .{ .codepoint = 0xA2, .quarter_points = 15 },
    .{ .codepoint = 0xA3, .quarter_points = 30 },
    .{ .codepoint = 0xA4, .quarter_points = 9 },
    .{ .codepoint = 0xA5, .quarter_points = 39 },
    .{ .codepoint = 0xA6, .quarter_points = 27 },
    .{ .codepoint = 0xA7, .quarter_points = 42 },
    .{ .codepoint = 0xA8, .quarter_points = 42 },
    .{ .codepoint = 0xA9, .quarter_points = 42 },
    .{ .codepoint = 0xAA, .quarter_points = 42 },
    .{ .codepoint = 0xAB, .quarter_points = 57 },
    .{ .codepoint = 0xAC, .quarter_points = 54 },
    .{ .codepoint = 0xAD, .quarter_points = 0 },
    .{ .codepoint = 0xAE, .quarter_points = 54 },
    .{ .codepoint = 0xAF, .quarter_points = 33 },
    .{ .codepoint = 0xB0, .quarter_points = 21 },
    .{ .codepoint = 0xB1, .quarter_points = 30 },
    .{ .codepoint = 0xB2, .quarter_points = 24 },
    .{ .codepoint = 0xB3, .quarter_points = 30 },
    .{ .codepoint = 0xB4, .quarter_points = 30 },
    .{ .codepoint = 0xB5, .quarter_points = 39 },
    .{ .codepoint = 0xB6, .quarter_points = 27 },
    .{ .codepoint = 0xB7, .quarter_points = 27 },
    .{ .codepoint = 0xB8, .quarter_points = 30 },
    .{ .codepoint = 0xB9, .quarter_points = 30 },
    .{ .codepoint = 0xBA, .quarter_points = 30 },
    .{ .codepoint = 0xBB, .quarter_points = 30 },
    .{ .codepoint = 0xBC, .quarter_points = 57 },
    .{ .codepoint = 0xBD, .quarter_points = 33 },
    .{ .codepoint = 0xBE, .quarter_points = 57 },
    .{ .codepoint = 0xBF, .quarter_points = 36 },
    .{ .codepoint = 0xC0, .quarter_points = 45 },
    .{ .codepoint = 0xC1, .quarter_points = 39 },
    .{ .codepoint = 0xC2, .quarter_points = 45 },
    .{ .codepoint = 0xC3, .quarter_points = 54 },
    .{ .codepoint = 0xC4, .quarter_points = 42 },
    .{ .codepoint = 0xC5, .quarter_points = 42 },
    .{ .codepoint = 0xC6, .quarter_points = 45 },
    .{ .codepoint = 0xC7, .quarter_points = 42 },
    .{ .codepoint = 0xC8, .quarter_points = 42 },
    .{ .codepoint = 0xC9, .quarter_points = 39 },
    .{ .codepoint = 0xCA, .quarter_points = 39 },
    .{ .codepoint = 0xCB, .quarter_points = 39 },
    .{ .codepoint = 0xCC, .quarter_points = 39 },
    .{ .codepoint = 0xCD, .quarter_points = 39 },
    .{ .codepoint = 0xCE, .quarter_points = 39 },
    .{ .codepoint = 0xCF, .quarter_points = 39 },
    .{ .codepoint = 0xD0, .quarter_points = 42 },
    .{ .codepoint = 0xD1, .quarter_points = 39 },
    .{ .codepoint = 0xD2, .quarter_points = 45 },
    .{ .codepoint = 0xD3, .quarter_points = 45 },
    .{ .codepoint = 0xD4, .quarter_points = 51 },
    .{ .codepoint = 0xD5, .quarter_points = 45 },
    .{ .codepoint = 0xD6, .quarter_points = 30 },
    .{ .codepoint = 0xD7, .quarter_points = 15 },
    .{ .codepoint = 0xD8, .quarter_points = 39 },
    .{ .codepoint = 0xD9, .quarter_points = 33 },
    .{ .codepoint = 0xDA, .quarter_points = 33 },
    .{ .codepoint = 0xDB, .quarter_points = 57 },
    .{ .codepoint = 0xDC, .quarter_points = 54 },
    .{ .codepoint = 0xDD, .quarter_points = 33 },
    .{ .codepoint = 0xDE, .quarter_points = 54 },
    .{ .codepoint = 0xDF, .quarter_points = 33 },
    .{ .codepoint = 0xE0, .quarter_points = 27 },
    .{ .codepoint = 0xE1, .quarter_points = 18 },
    .{ .codepoint = 0xE2, .quarter_points = 45 },
    .{ .codepoint = 0xE3, .quarter_points = 45 },
    .{ .codepoint = 0xE4, .quarter_points = 45 },
    .{ .codepoint = 0xE5, .quarter_points = 39 },
    .{ .codepoint = 0xE6, .quarter_points = 21 },
    .{ .codepoint = 0xE7, .quarter_points = 21 },
    .{ .codepoint = 0xE8, .quarter_points = 21 },
    .{ .codepoint = 0xE9, .quarter_points = 21 },
    .{ .codepoint = 0xEA, .quarter_points = 21 },
    .{ .codepoint = 0xEB, .quarter_points = 21 },
    .{ .codepoint = 0xEC, .quarter_points = 27 },
    .{ .codepoint = 0xED, .quarter_points = 27 },
    .{ .codepoint = 0xEE, .quarter_points = 27 },
    .{ .codepoint = 0xEF, .quarter_points = 27 },
    .{ .codepoint = 0xF0, .quarter_points = 33 },
    .{ .codepoint = 0xF1, .quarter_points = 18 },
    .{ .codepoint = 0xF2, .quarter_points = 15 },
    .{ .codepoint = 0xF3, .quarter_points = 39 },
    .{ .codepoint = 0xF4, .quarter_points = 39 },
    .{ .codepoint = 0xF5, .quarter_points = 39 },
    .{ .codepoint = 0xF6, .quarter_points = 21 },
    .{ .codepoint = 0xF7, .quarter_points = 21 },
    .{ .codepoint = 0xF8, .quarter_points = 21 },
    .{ .codepoint = 0xF9, .quarter_points = 21 },
    .{ .codepoint = 0xFA, .quarter_points = 21 },
    .{ .codepoint = 0xFB, .quarter_points = 21 },
    .{ .codepoint = 0xFC, .quarter_points = 27 },
    .{ .codepoint = 0xFD, .quarter_points = 27 },
    .{ .codepoint = 0xFE, .quarter_points = 27 },
    .{ .codepoint = 0xFF, .quarter_points = 30 },
    .{ .codepoint = 0x152, .quarter_points = 57 },
    .{ .codepoint = 0x153, .quarter_points = 48 },
    .{ .codepoint = 0x160, .quarter_points = 30 },
    .{ .codepoint = 0x161, .quarter_points = 21 },
    .{ .codepoint = 0x178, .quarter_points = 42 },
    .{ .codepoint = 0x192, .quarter_points = 27 },
    .{ .codepoint = 0x2C6, .quarter_points = 18 },
    .{ .codepoint = 0x2DC, .quarter_points = 18 },
    .{ .codepoint = 0x391, .quarter_points = 42 },
    .{ .codepoint = 0x392, .quarter_points = 39 },
    .{ .codepoint = 0x393, .quarter_points = 36 },
    .{ .codepoint = 0x394, .quarter_points = 33 },
    .{ .codepoint = 0x395, .quarter_points = 36 },
    .{ .codepoint = 0x396, .quarter_points = 36 },
    .{ .codepoint = 0x397, .quarter_points = 42 },
    .{ .codepoint = 0x398, .quarter_points = 42 },
    .{ .codepoint = 0x399, .quarter_points = 18 },
    .{ .codepoint = 0x39A, .quarter_points = 42 },
    .{ .codepoint = 0x39B, .quarter_points = 39 },
    .{ .codepoint = 0x39C, .quarter_points = 51 },
    .{ .codepoint = 0x39D, .quarter_points = 42 },
    .{ .codepoint = 0x39E, .quarter_points = 36 },
    .{ .codepoint = 0x39F, .quarter_points = 39 },
    .{ .codepoint = 0x3A0, .quarter_points = 45 },
    .{ .codepoint = 0x3A1, .quarter_points = 30 },
    .{ .codepoint = 0x3A3, .quarter_points = 33 },
    .{ .codepoint = 0x3A4, .quarter_points = 33 },
    .{ .codepoint = 0x3A5, .quarter_points = 39 },
    .{ .codepoint = 0x3A6, .quarter_points = 42 },
    .{ .codepoint = 0x3A7, .quarter_points = 39 },
    .{ .codepoint = 0x3A8, .quarter_points = 45 },
    .{ .codepoint = 0x3A9, .quarter_points = 42 },
    .{ .codepoint = 0x3B1, .quarter_points = 36 },
    .{ .codepoint = 0x3B2, .quarter_points = 30 },
    .{ .codepoint = 0x3B3, .quarter_points = 33 },
    .{ .codepoint = 0x3B4, .quarter_points = 27 },
    .{ .codepoint = 0x3B5, .quarter_points = 24 },
    .{ .codepoint = 0x3B6, .quarter_points = 27 },
    .{ .codepoint = 0x3B7, .quarter_points = 33 },
    .{ .codepoint = 0x3B8, .quarter_points = 30 },
    .{ .codepoint = 0x3B9, .quarter_points = 18 },
    .{ .codepoint = 0x3BA, .quarter_points = 30 },
    .{ .codepoint = 0x3BB, .quarter_points = 30 },
    .{ .codepoint = 0x3BC, .quarter_points = 33 },
    .{ .codepoint = 0x3BD, .quarter_points = 30 },
    .{ .codepoint = 0x3BE, .quarter_points = 27 },
    .{ .codepoint = 0x3BF, .quarter_points = 30 },
    .{ .codepoint = 0x3C0, .quarter_points = 30 },
    .{ .codepoint = 0x3C1, .quarter_points = 30 },
    .{ .codepoint = 0x3C2, .quarter_points = 24 },
    .{ .codepoint = 0x3C3, .quarter_points = 33 },
    .{ .codepoint = 0x3C4, .quarter_points = 24 },
    .{ .codepoint = 0x3C5, .quarter_points = 33 },
    .{ .codepoint = 0x3C6, .quarter_points = 33 },
    .{ .codepoint = 0x3C7, .quarter_points = 30 },
    .{ .codepoint = 0x3C8, .quarter_points = 39 },
    .{ .codepoint = 0x3C9, .quarter_points = 39 },
    .{ .codepoint = 0x3D1, .quarter_points = 30 },
    .{ .codepoint = 0x3D2, .quarter_points = 36 },
    .{ .codepoint = 0x3D6, .quarter_points = 39 },
    .{ .codepoint = 0x2002, .quarter_points = 27 },
    .{ .codepoint = 0x2003, .quarter_points = 57 },
    .{ .codepoint = 0x2009, .quarter_points = 12 },
    .{ .codepoint = 0x200C, .quarter_points = 0 },
    .{ .codepoint = 0x200D, .quarter_points = 0 },
    .{ .codepoint = 0x200E, .quarter_points = 0 },
    .{ .codepoint = 0x200F, .quarter_points = 0 },
    .{ .codepoint = 0x2013, .quarter_points = 30 },
    .{ .codepoint = 0x2014, .quarter_points = 57 },
    .{ .codepoint = 0x2018, .quarter_points = 12 },
    .{ .codepoint = 0x2019, .quarter_points = 12 },
    .{ .codepoint = 0x201A, .quarter_points = 12 },
    .{ .codepoint = 0x201C, .quarter_points = 24 },
    .{ .codepoint = 0x201D, .quarter_points = 24 },
    .{ .codepoint = 0x201E, .quarter_points = 24 },
    .{ .codepoint = 0x2020, .quarter_points = 24 },
    .{ .codepoint = 0x2021, .quarter_points = 27 },
    .{ .codepoint = 0x2022, .quarter_points = 21 },
    .{ .codepoint = 0x2026, .quarter_points = 54 },
    .{ .codepoint = 0x2030, .quarter_points = 54 },
    .{ .codepoint = 0x2032, .quarter_points = 18 },
    .{ .codepoint = 0x2033, .quarter_points = 27 },
    .{ .codepoint = 0x2039, .quarter_points = 18 },
    .{ .codepoint = 0x203A, .quarter_points = 18 },
    .{ .codepoint = 0x203E, .quarter_points = 27 },
    .{ .codepoint = 0x2044, .quarter_points = 6 },
    .{ .codepoint = 0x20AC, .quarter_points = 42 },
    .{ .codepoint = 0x2111, .quarter_points = 39 },
    .{ .codepoint = 0x2118, .quarter_points = 48 },
    .{ .codepoint = 0x211C, .quarter_points = 45 },
    .{ .codepoint = 0x2122, .quarter_points = 57 },
    .{ .codepoint = 0x2135, .quarter_points = 45 },
    .{ .codepoint = 0x2190, .quarter_points = 45 },
    .{ .codepoint = 0x2191, .quarter_points = 42 },
    .{ .codepoint = 0x2192, .quarter_points = 45 },
    .{ .codepoint = 0x2193, .quarter_points = 42 },
    .{ .codepoint = 0x2194, .quarter_points = 57 },
    .{ .codepoint = 0x21B5, .quarter_points = 45 },
    .{ .codepoint = 0x21D0, .quarter_points = 45 },
    .{ .codepoint = 0x21D1, .quarter_points = 33 },
    .{ .codepoint = 0x21D2, .quarter_points = 45 },
    .{ .codepoint = 0x21D3, .quarter_points = 33 },
    .{ .codepoint = 0x21D4, .quarter_points = 51 },
    .{ .codepoint = 0x2200, .quarter_points = 48 },
    .{ .codepoint = 0x2202, .quarter_points = 30 },
    .{ .codepoint = 0x2203, .quarter_points = 36 },
    .{ .codepoint = 0x2205, .quarter_points = 48 },
    .{ .codepoint = 0x2207, .quarter_points = 45 },
    .{ .codepoint = 0x2208, .quarter_points = 39 },
    .{ .codepoint = 0x2209, .quarter_points = 39 },
    .{ .codepoint = 0x220B, .quarter_points = 39 },
    .{ .codepoint = 0x220F, .quarter_points = 48 },
    .{ .codepoint = 0x2211, .quarter_points = 45 },
    .{ .codepoint = 0x2212, .quarter_points = 45 },
    .{ .codepoint = 0x2217, .quarter_points = 39 },
    .{ .codepoint = 0x221A, .quarter_points = 30 },
    .{ .codepoint = 0x221D, .quarter_points = 39 },
    .{ .codepoint = 0x221E, .quarter_points = 42 },
    .{ .codepoint = 0x2220, .quarter_points = 42 },
    .{ .codepoint = 0x2227, .quarter_points = 45 },
    .{ .codepoint = 0x2228, .quarter_points = 45 },
    .{ .codepoint = 0x2229, .quarter_points = 45 },
    .{ .codepoint = 0x222A, .quarter_points = 45 },
    .{ .codepoint = 0x222B, .quarter_points = 33 },
    .{ .codepoint = 0x2234, .quarter_points = 48 },
    .{ .codepoint = 0x223C, .quarter_points = 45 },
    .{ .codepoint = 0x2245, .quarter_points = 45 },
    .{ .codepoint = 0x2248, .quarter_points = 45 },
    .{ .codepoint = 0x2260, .quarter_points = 45 },
    .{ .codepoint = 0x2261, .quarter_points = 45 },
    .{ .codepoint = 0x2264, .quarter_points = 45 },
    .{ .codepoint = 0x2265, .quarter_points = 45 },
    .{ .codepoint = 0x2282, .quarter_points = 45 },
    .{ .codepoint = 0x2283, .quarter_points = 45 },
    .{ .codepoint = 0x2284, .quarter_points = 45 },
    .{ .codepoint = 0x2286, .quarter_points = 45 },
    .{ .codepoint = 0x2287, .quarter_points = 45 },
    .{ .codepoint = 0x2295, .quarter_points = 45 },
    .{ .codepoint = 0x2297, .quarter_points = 45 },
    .{ .codepoint = 0x22A5, .quarter_points = 39 },
    .{ .codepoint = 0x22C5, .quarter_points = 33 },
    .{ .codepoint = 0x2308, .quarter_points = 15 },
    .{ .codepoint = 0x2309, .quarter_points = 15 },
    .{ .codepoint = 0x230A, .quarter_points = 15 },
    .{ .codepoint = 0x230B, .quarter_points = 15 },
    .{ .codepoint = 0x2329, .quarter_points = 18 },
    .{ .codepoint = 0x232A, .quarter_points = 18 },
    .{ .codepoint = 0x25CA, .quarter_points = 27 },
    .{ .codepoint = 0x2660, .quarter_points = 36 },
    .{ .codepoint = 0x2663, .quarter_points = 42 },
    .{ .codepoint = 0x2665, .quarter_points = 39 },
    .{ .codepoint = 0x2666, .quarter_points = 33 },
};

test "Symbol metrics reproduce Graphviz fixture widths" {
    try std.testing.expectApproxEqAbs(
        @as(f64, 208.0),
        symbolLabelWidth("αβγδεζηθικλμνξοπρςστυφχψωϒϖ", 14).?,
        0.001,
    );
    try std.testing.expectApproxEqAbs(@as(f64, 70), symbolLabelWidth("for all: ∀", 14).?, 0.001);
    try std.testing.expectApproxEqAbs(@as(f64, 122), symbolLabelWidth("proportional to: ∝", 14).?, 0.001);
    try std.testing.expectApproxEqAbs(@as(f64, 105), symbolLabelWidth("for all: ∀", 21).?, 0.001);
}

test "Symbol metrics reject uncovered codepoints" {
    try std.testing.expect(symbolLabelWidth("CJK 漢", 14) == null);
}
